---
- hosts: 192.168.33.30
  become_user: root
  become: yes
  become_method: sudo
  roles:
    - ./roles/install-java8
    - ./roles/install-maven3
    - ./roles/install-google-chrome
  vars:
    coffeeIP: "{{ lookup('env', 'COFFEEMAKER') }}"
  tasks:
  #  - name: install maven
  #    apt: pkg=maven state=latest update_cache=yes cache_valid_time=3600




  #  - name: download maven
  #    get_url:
  #      url: http://www-eu.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
  #      dest: /home/vagrant/maven.tar.gz
  #      mode: u+rwx

  #  - name: install maven
  #    apt:
  #      deb: /home/vagrant/maven.tar.gz



    - name: set the IP address of coffeemaker in webtest.java8
      lineinfile:
        path: /vagrant_data/src/test/java/selenium/tests/WebTest.java
        regexp: 'ROOT = '
        line: '    private final String     ROOT = "http://{{coffeeIP}}:8080/";'

    - name: change to webtest.java to ensure that chrome runs
      lineinfile:
        path: /vagrant_data/src/test/java/selenium/tests/WebTest.java
        regexp: 'driver = '
        line: 'options.addArguments( "no-sandbox");driver = new ChromeDriver( options );'

    - debug: msg="{{coffeeIP}} is the environment variable"

    - name: run the mvn tests
      shell: cd /vagrant_data && mvn test
      register: result

    - debug: var=result.stdout_lines
